### ISSUE TITLE
.pkg file missing from rb2dx downloads

### ISSUE THREAD

**Issue by Ckman1288** [hmxmilohax/rock-band-2-deluxe#11]
I don't know if something has changed recently but I had to redownload the mod only to find that there is no longer the .pkg update file. Nothing else works so I'm hoping this is the right place to ask for help

**Comment by jnackmclain** [comment]
we no longer offer pkg files. you can find the latest nightly here that you can ftp to your console or overwrite in rpcs3 manually
https://nightly.link/hmxmilohax/rock-band-2-deluxe/workflows/build/main

**Comment by Ckman1288** [comment]
> we no longer offer pkg files. you can find the latest nightly here that you can ftp to your console or overwrite in rpcs3 manually https://nightly.link/hmxmilohax/rock-band-2-deluxe/workflows/build/main

So sorry to bother again but how would you go about manually overwrite in rpcs3?

**Comment by jnackmclain** [comment]
On ps3/rpcs3, copy all files to "/dev_hdd0/game/BLUS30147/" Match the file system and overwrite the files.

**Comment by Ckman1288** [comment]
> On ps3/rpcs3, copy all files to "/dev_hdd0/game/BLUS30147/" Match the file system and overwrite the files.

Thanks so much!
